# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0243f7e3c8004ca4cf207dd749873e14e018ffddd1f430902596edde1d61f1cc4a69c3198231f95af620107a328f5708284b5ac19bad8e6f3d6f6ab98ecd431e

test:
  secret_key_base: 8461604cf6a6d1fcd7afa7ba4dbb415fe7dd16c749ebf23372129007ccf6ae9a933f1e8df61155c9ffa6ff7d7b9e045847a48dc4d6e170afb5d30396dd6aff5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
